version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: smartscoredb
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: smartscorebot
    depends_on:
      - db
      - flaskserver
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/smartscoredb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: '1234'
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

  flaskserver:
    build: ./flaskserver
    container_name: flaskserver
    ports:
      - "5000:5000"
