spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 100scorebot@gmail.com
    password: sohi qhtd eprg pkhk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smartscoredb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  thymeleaf:
    cache: false

google:
  cloud:
    vision:
      enabled: true # true로 설정하고 인증 정보를 설정해야 OCR 기능 사용 가능
      credentials:
        path: C:/gcp/smartscore-483706-b7d67bf8ad27.json # 인증 파일 경로 (예: C:/path/to/credentials.json)
